FROM nginx:1.15.12-alpine

# Remove a configuração padrão para não dar conflito
RUN rm /etc/nginx/conf.d/default.conf

# Copia o seu arquivo que está no GitHub para dentro da imagem
COPY ./nginx-conf/default.conf /etc/nginx/conf.d/default.conf